apiVersion: v1
clusters:
  - cluster:
      certificate-authority: /home/quyendv/.minikube/ca.crt
      extensions:
        - extension:
            last-update: Tue, 02 Jul 2024 12:30:00 +07
            provider: minikube.sigs.k8s.io
            version: v1.32.0
          name: cluster_info
      server: https://127.0.0.1:32784
    name: minikube
contexts:
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Tue, 02 Jul 2024 12:30:00 +07
            provider: minikube.sigs.k8s.io
            version: v1.32.0
          name: context_info
      namespace: default
      user: minikube
    name: minikube
  - context:
      cluster: minikube
      extensions:
        - extension:
            last-update: Tue, 02 Jul 2024 12:30:00 +07
            provider: minikube.sigs.k8s.io
            version: v1.32.0
          name: context_info
      namespace: development
      user: viewer
    name: viewer@minikube
# current-context: minikube
current-context: viewer@minikube
kind: Config
preferences: {}
users:
  - name: minikube
    user:
      client-certificate: /home/quyendv/.minikube/profiles/minikube/client.crt
      client-key: /home/quyendv/.minikube/profiles/minikube/client.key
  - name: viewer
    user:
      token: <token here>
  - name: developer
    user:
      token: <token here>
  - name: admin
    user:
      token: <token here>
